name: CI
on:
  push:
  schedule:
  - cron: '0 0 * * 1'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions-rs/cargo@v1
    - name: configure git
      run: |
        git config --global user.name "SichangHe"
        git config --global user.email "sichanghe@users.noreply.github.com"
    - uses: swatinem/rust-cache@v2
    - name: Install mdbook
      run: |
        cargo install mdbook
        which mdbook
    - name: Install mdbook-katex
      run: |
        cargo install mdbook-katex
        which mdbook-katex
    - name: Install mdbook-toc
      run: |
        cargo install mdbook-toc
        which mdbook-toc
    - name: push
      run: |
        rm -rf bin
        mkdir bin
        mv ~/.cargo/bin/mdbook bin
        mv ~/.cargo/bin/mdbook-katex bin
        mv ~/.cargo/bin/mdbook-toc bin
        git add bin
        git commit --allow-empty -m "build $GITHUB_SHA"
        git push -f
